name: CI/CD Pipeline Diabetes
on: [push]
jobs:
  build-and-train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install pandas scikit-learn mlflow dagshub joblib prometheus-client

    # Path langsung ke folder (karena sudah di root)
    - name: Run Preprocessing
      run: |
        cd Eksperimen_SML_GalihRasyid/preprocessing
        python automate_GalihRasyid.py
    
    - name: Upload Dataset Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dataset-preprocessed
        path: Eksperimen_SML_GalihRasyid/preprocessing/diabetes_preprocessing/diabetes_clean.csv

    - name: Run Training
      run: |
        cd Workflow-CI/MLProject
        python modelling.py
        
    - name: Upload Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: model-artifact
        path: Workflow-CI/MLProject/model.pkl